
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x80}\xce\x04\x1b\xd6\x1d\xa2\n#\xe15W-\xbc\x1f'
    
_lr_action_items = {'%':([4,5,6,7,8,16,17,18,19,20,21,22,23,24,],[10,-8,-7,10,-11,-9,10,-5,10,-3,10,-4,-6,-10,]),')':([5,6,7,8,16,17,18,19,20,21,22,23,24,],[-8,-7,16,-11,-9,24,-5,-1,-3,-2,-4,-6,-10,]),'(':([0,1,2,3,9,10,11,12,13,14,15,],[1,1,1,9,1,1,1,1,1,1,1,]),'+':([4,5,6,7,8,16,17,18,19,20,21,22,23,24,],[11,-8,-7,11,-11,-9,11,-5,-1,-3,-2,-4,-6,-10,]),'*':([4,5,6,7,8,16,17,18,19,20,21,22,23,24,],[12,-8,-7,12,-11,-9,12,-5,12,-3,12,-4,-6,-10,]),'-':([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,],[2,2,2,13,-8,-7,13,-11,2,2,2,2,2,2,2,-9,13,-5,-1,-3,-2,-4,-6,-10,]),'/':([4,5,6,7,8,16,17,18,19,20,21,22,23,24,],[14,-8,-7,14,-11,-9,14,-5,14,-3,14,-4,-6,-10,]),'ABS':([0,1,2,9,10,11,12,13,14,15,],[3,3,3,3,3,3,3,3,3,3,]),'INTCONST':([0,1,2,9,10,11,12,13,14,15,],[5,5,5,5,5,5,5,5,5,5,]),'E':([4,5,6,7,8,16,17,18,19,20,21,22,23,24,],[15,-8,-7,15,15,-9,15,15,15,15,15,15,15,-10,]),'IDENTIFIER':([0,1,2,9,10,11,12,13,14,15,],[6,6,6,6,6,6,6,6,6,6,]),'$end':([4,5,6,8,16,18,19,20,21,22,23,24,],[0,-8,-7,-11,-9,-5,-1,-3,-2,-4,-6,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,1,2,9,10,11,12,13,14,15,],[4,7,8,17,18,19,20,21,22,23,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp + exp','exp',3,'p_binop','/Users/aallai/code/group-f/tiny/ply/parser.py',17),
  ('exp -> exp - exp','exp',3,'p_binop','/Users/aallai/code/group-f/tiny/ply/parser.py',18),
  ('exp -> exp * exp','exp',3,'p_binop','/Users/aallai/code/group-f/tiny/ply/parser.py',19),
  ('exp -> exp / exp','exp',3,'p_binop','/Users/aallai/code/group-f/tiny/ply/parser.py',20),
  ('exp -> exp % exp','exp',3,'p_binop','/Users/aallai/code/group-f/tiny/ply/parser.py',21),
  ('exp -> exp E exp','exp',3,'p_binop','/Users/aallai/code/group-f/tiny/ply/parser.py',22),
  ('exp -> IDENTIFIER','exp',1,'p_ident','/Users/aallai/code/group-f/tiny/ply/parser.py',28),
  ('exp -> INTCONST','exp',1,'p_intconst','/Users/aallai/code/group-f/tiny/ply/parser.py',34),
  ('exp -> ( exp )','exp',3,'p_group','/Users/aallai/code/group-f/tiny/ply/parser.py',40),
  ('exp -> ABS ( exp )','exp',4,'p_abs','/Users/aallai/code/group-f/tiny/ply/parser.py',46),
  ('exp -> - exp','exp',2,'p_unary_minus','/Users/aallai/code/group-f/tiny/ply/parser.py',52),
]
